export interface Boot {
    id: number;
    rfid: String;
    sensorId: number;
    sensorSerialNumber: String;
    macAddress: String;
    ecuDeviceId: String;
    pressure1: number;
    pressure2: number;
    pressure3: number;
    pressure4: number;
    pressure5: number;
    targetPressures: number[];
    minPressures: number[];
    maxPressures: number[];
    status: Boolean[];
    r_temp_avg: number;
    externalTemperatureSensorAvg: number;
    adValues: String;
    timeStamp: Date;
    userMatrikelNumber: number;
  };